name: Issues workflow
on:
  issues:
    types: [opened, edited, deleted]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJson(github.event) }}"